# Generated by Django 3.0.6 on 2020-08-12 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='country',
            table='country',
        ),
    ]
